version: "3.4"

volumes:
  trueblocks_data: { }


x-environment: &chiffra-env
  - ETHERSCAN_KEY=GM679E3GW2RZEPYE7EWGJ9MINEQBCYSFW4
  - RPC_PROVIDER=http://erigon.dappnode:8545


x-volumes: &chiffa-share
  - "./trueblocks_data:/root/.local/share"

x-service: &chiffra
  build:
    context: build
  restart: unless-stopped



services:
  chiffra:
    <<: *chiffra
    restart: unless-stopped
    environment: *chiffra-env
    volumes: *chiffa-share
    stdin_open: true # docker run -i
    tty: true
  explorer:
    <<: *chiffra
    volumes: *chiffa-share
    restart: unless-stopped
    environment:
      - ETHERSCAN_KEY=GM679E3GW2RZEPYE7EWGJ9MINEQBCYSFW4
      - RPC_PROVIDER=http://erigon.dappnode:8545
      - IS_API="1"
    ports:
      - "8080:8080"
    depends_on:
      - chiffra
